version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs-requirements.txt
    - method: pip
      path: .
