#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker build . -t guillotina/guillotina:latest
docker tag guillotina/guillotina:latest guillotina/guillotina:$(cat VERSION)
docker push guillotina/guillotina:latest
docker push guillotina/guillotina:$(cat VERSION)
