[tool.black]
line-length = 110
target_version = ['py37']
include = '''\.py$'''
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | guillotina/cookiecutter
    | lib
    | build
    | bin
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.mypy]
exclude = ["guillotina/cookiecutter/"]
ignore_missing_imports = true
