# content of pytest.ini
[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
norecursedirs = cookiecutter build _build
filterwarnings =
    ignore::ResourceWarning
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
markers =
    app_settings: customize app_settings for tests
    flaky: rerun flaky integration tests
