# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measures/protobuf/test.proto
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="measures/protobuf/test.proto",
    package="measure",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x1cmeasures/protobuf/test.proto\x12\x07measure\x1a\x1fgoogle/protobuf/timestamp.proto"\xc8\x01\n\nDublinCore\x12\x0c\n\x04tags\x18\x01 \x03(\t\x12\x31\n\rcreation_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0e\x65\x66\x66\x65\x63tive_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0f\x65xpiration_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x63reators\x18\x05 \x03(\tb\x06proto3',
    dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR],
)


_DUBLINCORE = _descriptor.Descriptor(
    name="DublinCore",
    full_name="measure.DublinCore",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="tags",
            full_name="measure.DublinCore.tags",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="creation_date",
            full_name="measure.DublinCore.creation_date",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="effective_date",
            full_name="measure.DublinCore.effective_date",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="expiration_date",
            full_name="measure.DublinCore.expiration_date",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="creators",
            full_name="measure.DublinCore.creators",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=75,
    serialized_end=275,
)

_DUBLINCORE.fields_by_name["creation_date"].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DUBLINCORE.fields_by_name["effective_date"].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DUBLINCORE.fields_by_name["expiration_date"].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name["DublinCore"] = _DUBLINCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DublinCore = _reflection.GeneratedProtocolMessageType(
    "DublinCore",
    (_message.Message,),
    {
        "DESCRIPTOR": _DUBLINCORE,
        "__module__": "measures.protobuf.test_pb2"
        # @@protoc_insertion_point(class_scope:measure.DublinCore)
    },
)
_sym_db.RegisterMessage(DublinCore)


# @@protoc_insertion_point(module_scope)
