class SMTP:
    def __init__(self, host: str, port: int):
        ...

    async def connect(self):
        ...

    async def login(self, username: str, password: str):
        ...

    async def starttls(self):
        ...
